// <auto-generated />
namespace ManagementCoach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class WTFPart4ButIReallyGetItThisTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WTFPart4ButIReallyGetItThisTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202212181225152_WTFPart4ButIReallyGetItThisTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
