// <auto-generated />
namespace ManagementCoach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RestArea2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestArea2));
        
        string IMigrationMetadata.Id
        {
            get { return "202212151414061_RestArea2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
